### PR TITLE
feat: add vite_asset_url helper

### PR DESCRIPTION
**Pull request by yegayazilim**
### Description 📖

Add vite_asset_url helper

### Background 📜

Needed url to the asset instead of path

### The Fix 🔨

By adding the appropriate tag helper

### CODE REVIEW

**Comment by ElMassimo** [comment]
Hi @yegayazilim!

Would you share your use case? Are you using non-CSS assets in mailers?

**Comment by yegayazilim** [comment]
> Hi @yegayazilim!
> 
> Would you share your use case? Are you using non-CSS assets in mailers?

Hi ElMassimo,
Yes, I am using images in mailers.

**Comment by ElMassimo** [comment]
Ok, sounds reasonable given both scripts and stylesheets can already render a URL if needed.

Would you add a test covering the usage of this new helper, and fix the Rubocop lint error?

**Comment by yegayazilim** [comment]
@ElMassimo,
I fixed Rubocop lint error. However, I am not sure about how to write test coverage. Can you help me?

**Comment by ElMassimo** [comment]
Thanks! No problem, I'll add a test in this pull request before merging.

**Comment by ElMassimo** [comment]
[release: vite_rails_legacy@3.0.5](https://github.com/ElMassimo/vite_ruby/commit/87ea065264c3348c430f3fc0bf3bc7e1ebba28ef)
[release: vite_rails@3.0.9](https://github.com/ElMassimo/vite_ruby/commit/5ba9b54a37a70a1f1abf6d4b11d8549540d7f6a4)

**Pull request merged**
